// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mqadmintest

import (
	"context"

	"github.com/konradheimel/kurator/api/v1alpha1"
	"github.com/konradheimel/kurator/internal/mqadmin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFactory creates a new instance of MockFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFactory {
	mock := &MockFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFactory is an autogenerated mock type for the Factory type
type MockFactory struct {
	mock.Mock
}

type MockFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFactory) EXPECT() *MockFactory_Expecter {
	return &MockFactory_Expecter{mock: &_m.Mock}
}

// ForConnection provides a mock function for the type MockFactory
func (_mock *MockFactory) ForConnection(ctx context.Context, conn *v1alpha1.QueueManagerConnection) (mqadmin.Admin, error) {
	ret := _mock.Called(ctx, conn)

	if len(ret) == 0 {
		panic("no return value specified for ForConnection")
	}

	var r0 mqadmin.Admin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.QueueManagerConnection) (mqadmin.Admin, error)); ok {
		return returnFunc(ctx, conn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.QueueManagerConnection) mqadmin.Admin); ok {
		r0 = returnFunc(ctx, conn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mqadmin.Admin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1alpha1.QueueManagerConnection) error); ok {
		r1 = returnFunc(ctx, conn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFactory_ForConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForConnection'
type MockFactory_ForConnection_Call struct {
	*mock.Call
}

// ForConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *v1alpha1.QueueManagerConnection
func (_e *MockFactory_Expecter) ForConnection(ctx interface{}, conn interface{}) *MockFactory_ForConnection_Call {
	return &MockFactory_ForConnection_Call{Call: _e.mock.On("ForConnection", ctx, conn)}
}

func (_c *MockFactory_ForConnection_Call) Run(run func(ctx context.Context, conn *v1alpha1.QueueManagerConnection)) *MockFactory_ForConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha1.QueueManagerConnection
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.QueueManagerConnection)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFactory_ForConnection_Call) Return(admin mqadmin.Admin, err error) *MockFactory_ForConnection_Call {
	_c.Call.Return(admin, err)
	return _c
}

func (_c *MockFactory_ForConnection_Call) RunAndReturn(run func(ctx context.Context, conn *v1alpha1.QueueManagerConnection) (mqadmin.Admin, error)) *MockFactory_ForConnection_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdmin creates a new instance of MockAdmin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdmin(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdmin {
	mock := &MockAdmin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdmin is an autogenerated mock type for the Admin type
type MockAdmin struct {
	mock.Mock
}

type MockAdmin_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdmin) EXPECT() *MockAdmin_Expecter {
	return &MockAdmin_Expecter{mock: &_m.Mock}
}

// DefineChannel provides a mock function for the type MockAdmin
func (_mock *MockAdmin) DefineChannel(ctx context.Context, spec mqadmin.ChannelSpec) error {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for DefineChannel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mqadmin.ChannelSpec) error); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdmin_DefineChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineChannel'
type MockAdmin_DefineChannel_Call struct {
	*mock.Call
}

// DefineChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - spec mqadmin.ChannelSpec
func (_e *MockAdmin_Expecter) DefineChannel(ctx interface{}, spec interface{}) *MockAdmin_DefineChannel_Call {
	return &MockAdmin_DefineChannel_Call{Call: _e.mock.On("DefineChannel", ctx, spec)}
}

func (_c *MockAdmin_DefineChannel_Call) Run(run func(ctx context.Context, spec mqadmin.ChannelSpec)) *MockAdmin_DefineChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mqadmin.ChannelSpec
		if args[1] != nil {
			arg1 = args[1].(mqadmin.ChannelSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdmin_DefineChannel_Call) Return(err error) *MockAdmin_DefineChannel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdmin_DefineChannel_Call) RunAndReturn(run func(ctx context.Context, spec mqadmin.ChannelSpec) error) *MockAdmin_DefineChannel_Call {
	_c.Call.Return(run)
	return _c
}

// DefineQueue provides a mock function for the type MockAdmin
func (_mock *MockAdmin) DefineQueue(ctx context.Context, spec mqadmin.QueueSpec) error {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for DefineQueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mqadmin.QueueSpec) error); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdmin_DefineQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineQueue'
type MockAdmin_DefineQueue_Call struct {
	*mock.Call
}

// DefineQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - spec mqadmin.QueueSpec
func (_e *MockAdmin_Expecter) DefineQueue(ctx interface{}, spec interface{}) *MockAdmin_DefineQueue_Call {
	return &MockAdmin_DefineQueue_Call{Call: _e.mock.On("DefineQueue", ctx, spec)}
}

func (_c *MockAdmin_DefineQueue_Call) Run(run func(ctx context.Context, spec mqadmin.QueueSpec)) *MockAdmin_DefineQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mqadmin.QueueSpec
		if args[1] != nil {
			arg1 = args[1].(mqadmin.QueueSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdmin_DefineQueue_Call) Return(err error) *MockAdmin_DefineQueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdmin_DefineQueue_Call) RunAndReturn(run func(ctx context.Context, spec mqadmin.QueueSpec) error) *MockAdmin_DefineQueue_Call {
	_c.Call.Return(run)
	return _c
}

// DefineTopic provides a mock function for the type MockAdmin
func (_mock *MockAdmin) DefineTopic(ctx context.Context, spec mqadmin.TopicSpec) error {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for DefineTopic")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mqadmin.TopicSpec) error); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdmin_DefineTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DefineTopic'
type MockAdmin_DefineTopic_Call struct {
	*mock.Call
}

// DefineTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - spec mqadmin.TopicSpec
func (_e *MockAdmin_Expecter) DefineTopic(ctx interface{}, spec interface{}) *MockAdmin_DefineTopic_Call {
	return &MockAdmin_DefineTopic_Call{Call: _e.mock.On("DefineTopic", ctx, spec)}
}

func (_c *MockAdmin_DefineTopic_Call) Run(run func(ctx context.Context, spec mqadmin.TopicSpec)) *MockAdmin_DefineTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mqadmin.TopicSpec
		if args[1] != nil {
			arg1 = args[1].(mqadmin.TopicSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdmin_DefineTopic_Call) Return(err error) *MockAdmin_DefineTopic_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdmin_DefineTopic_Call) RunAndReturn(run func(ctx context.Context, spec mqadmin.TopicSpec) error) *MockAdmin_DefineTopic_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteChannel provides a mock function for the type MockAdmin
func (_mock *MockAdmin) DeleteChannel(ctx context.Context, spec mqadmin.ChannelSpec) error {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChannel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mqadmin.ChannelSpec) error); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdmin_DeleteChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChannel'
type MockAdmin_DeleteChannel_Call struct {
	*mock.Call
}

// DeleteChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - spec mqadmin.ChannelSpec
func (_e *MockAdmin_Expecter) DeleteChannel(ctx interface{}, spec interface{}) *MockAdmin_DeleteChannel_Call {
	return &MockAdmin_DeleteChannel_Call{Call: _e.mock.On("DeleteChannel", ctx, spec)}
}

func (_c *MockAdmin_DeleteChannel_Call) Run(run func(ctx context.Context, spec mqadmin.ChannelSpec)) *MockAdmin_DeleteChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mqadmin.ChannelSpec
		if args[1] != nil {
			arg1 = args[1].(mqadmin.ChannelSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdmin_DeleteChannel_Call) Return(err error) *MockAdmin_DeleteChannel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdmin_DeleteChannel_Call) RunAndReturn(run func(ctx context.Context, spec mqadmin.ChannelSpec) error) *MockAdmin_DeleteChannel_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQueue provides a mock function for the type MockAdmin
func (_mock *MockAdmin) DeleteQueue(ctx context.Context, spec mqadmin.QueueSpec) error {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mqadmin.QueueSpec) error); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdmin_DeleteQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQueue'
type MockAdmin_DeleteQueue_Call struct {
	*mock.Call
}

// DeleteQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - spec mqadmin.QueueSpec
func (_e *MockAdmin_Expecter) DeleteQueue(ctx interface{}, spec interface{}) *MockAdmin_DeleteQueue_Call {
	return &MockAdmin_DeleteQueue_Call{Call: _e.mock.On("DeleteQueue", ctx, spec)}
}

func (_c *MockAdmin_DeleteQueue_Call) Run(run func(ctx context.Context, spec mqadmin.QueueSpec)) *MockAdmin_DeleteQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mqadmin.QueueSpec
		if args[1] != nil {
			arg1 = args[1].(mqadmin.QueueSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdmin_DeleteQueue_Call) Return(err error) *MockAdmin_DeleteQueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdmin_DeleteQueue_Call) RunAndReturn(run func(ctx context.Context, spec mqadmin.QueueSpec) error) *MockAdmin_DeleteQueue_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTopic provides a mock function for the type MockAdmin
func (_mock *MockAdmin) DeleteTopic(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTopic")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdmin_DeleteTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTopic'
type MockAdmin_DeleteTopic_Call struct {
	*mock.Call
}

// DeleteTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockAdmin_Expecter) DeleteTopic(ctx interface{}, name interface{}) *MockAdmin_DeleteTopic_Call {
	return &MockAdmin_DeleteTopic_Call{Call: _e.mock.On("DeleteTopic", ctx, name)}
}

func (_c *MockAdmin_DeleteTopic_Call) Run(run func(ctx context.Context, name string)) *MockAdmin_DeleteTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdmin_DeleteTopic_Call) Return(err error) *MockAdmin_DeleteTopic_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdmin_DeleteTopic_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockAdmin_DeleteTopic_Call {
	_c.Call.Return(run)
	return _c
}

// GetChannel provides a mock function for the type MockAdmin
func (_mock *MockAdmin) GetChannel(ctx context.Context, spec mqadmin.ChannelSpec) (*mqadmin.ChannelState, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for GetChannel")
	}

	var r0 *mqadmin.ChannelState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mqadmin.ChannelSpec) (*mqadmin.ChannelState, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mqadmin.ChannelSpec) *mqadmin.ChannelState); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mqadmin.ChannelState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mqadmin.ChannelSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdmin_GetChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannel'
type MockAdmin_GetChannel_Call struct {
	*mock.Call
}

// GetChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - spec mqadmin.ChannelSpec
func (_e *MockAdmin_Expecter) GetChannel(ctx interface{}, spec interface{}) *MockAdmin_GetChannel_Call {
	return &MockAdmin_GetChannel_Call{Call: _e.mock.On("GetChannel", ctx, spec)}
}

func (_c *MockAdmin_GetChannel_Call) Run(run func(ctx context.Context, spec mqadmin.ChannelSpec)) *MockAdmin_GetChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mqadmin.ChannelSpec
		if args[1] != nil {
			arg1 = args[1].(mqadmin.ChannelSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdmin_GetChannel_Call) Return(channelState *mqadmin.ChannelState, err error) *MockAdmin_GetChannel_Call {
	_c.Call.Return(channelState, err)
	return _c
}

func (_c *MockAdmin_GetChannel_Call) RunAndReturn(run func(ctx context.Context, spec mqadmin.ChannelSpec) (*mqadmin.ChannelState, error)) *MockAdmin_GetChannel_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueue provides a mock function for the type MockAdmin
func (_mock *MockAdmin) GetQueue(ctx context.Context, spec mqadmin.QueueSpec) (*mqadmin.QueueState, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for GetQueue")
	}

	var r0 *mqadmin.QueueState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mqadmin.QueueSpec) (*mqadmin.QueueState, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mqadmin.QueueSpec) *mqadmin.QueueState); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mqadmin.QueueState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mqadmin.QueueSpec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdmin_GetQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueue'
type MockAdmin_GetQueue_Call struct {
	*mock.Call
}

// GetQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - spec mqadmin.QueueSpec
func (_e *MockAdmin_Expecter) GetQueue(ctx interface{}, spec interface{}) *MockAdmin_GetQueue_Call {
	return &MockAdmin_GetQueue_Call{Call: _e.mock.On("GetQueue", ctx, spec)}
}

func (_c *MockAdmin_GetQueue_Call) Run(run func(ctx context.Context, spec mqadmin.QueueSpec)) *MockAdmin_GetQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mqadmin.QueueSpec
		if args[1] != nil {
			arg1 = args[1].(mqadmin.QueueSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdmin_GetQueue_Call) Return(queueState *mqadmin.QueueState, err error) *MockAdmin_GetQueue_Call {
	_c.Call.Return(queueState, err)
	return _c
}

func (_c *MockAdmin_GetQueue_Call) RunAndReturn(run func(ctx context.Context, spec mqadmin.QueueSpec) (*mqadmin.QueueState, error)) *MockAdmin_GetQueue_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopic provides a mock function for the type MockAdmin
func (_mock *MockAdmin) GetTopic(ctx context.Context, name string) (*mqadmin.TopicState, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetTopic")
	}

	var r0 *mqadmin.TopicState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*mqadmin.TopicState, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *mqadmin.TopicState); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mqadmin.TopicState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdmin_GetTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopic'
type MockAdmin_GetTopic_Call struct {
	*mock.Call
}

// GetTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockAdmin_Expecter) GetTopic(ctx interface{}, name interface{}) *MockAdmin_GetTopic_Call {
	return &MockAdmin_GetTopic_Call{Call: _e.mock.On("GetTopic", ctx, name)}
}

func (_c *MockAdmin_GetTopic_Call) Run(run func(ctx context.Context, name string)) *MockAdmin_GetTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdmin_GetTopic_Call) Return(topicState *mqadmin.TopicState, err error) *MockAdmin_GetTopic_Call {
	_c.Call.Return(topicState, err)
	return _c
}

func (_c *MockAdmin_GetTopic_Call) RunAndReturn(run func(ctx context.Context, name string) (*mqadmin.TopicState, error)) *MockAdmin_GetTopic_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockAdmin
func (_mock *MockAdmin) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdmin_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockAdmin_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdmin_Expecter) Ping(ctx interface{}) *MockAdmin_Ping_Call {
	return &MockAdmin_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockAdmin_Ping_Call) Run(run func(ctx context.Context)) *MockAdmin_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdmin_Ping_Call) Return(err error) *MockAdmin_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdmin_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockAdmin_Ping_Call {
	_c.Call.Return(run)
	return _c
}
