---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - messaging.kurator.dev
  resources:
  - authorityrecords
  - channelauthrules
  - channels
  - queuemanagerconnections
  - queues
  - topics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - messaging.kurator.dev
  resources:
  - authorityrecords/finalizers
  - channelauthrules/finalizers
  - channels/finalizers
  - queuemanagerconnections/finalizers
  - queues/finalizers
  - topics/finalizers
  verbs:
  - update
- apiGroups:
  - messaging.kurator.dev
  resources:
  - authorityrecords/status
  - channelauthrules/status
  - channels/status
  - queuemanagerconnections/status
  - queues/status
  - topics/status
  verbs:
  - get
  - patch
  - update
