## Append samples of your project ##
resources:
- messaging_v1alpha1_queuemanagerconnection.yaml
- messaging_v1alpha1_queue.yaml
- messaging_v1alpha1_queue_alias.yaml
- messaging_v1alpha1_queue_remote.yaml
- messaging_v1alpha1_topic.yaml
- messaging_v1alpha1_channel.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
