apiVersion: messaging.mkurator.dev/v1alpha1
kind: Queue
metadata:
  name: orders-remote
  namespace: mkurator-system
spec:
  connectionRef:
    name: qm1
  queueName: APP.ORDERS.REMOTE
  type: remote
  xmitQueue: SYSTEM.DEFAULT.XMIT.QUEUE
  remoteQueueManager: QM1
  attributes:
    rname: APP.ORDERS
    descr: Remote definition to APP.ORDERS on QM1 (local demo)
