apiVersion: messaging.mkurator.dev/v1alpha1
kind: Channel
metadata:
  name: orders-app
  namespace: mkurator-system
spec:
  connectionRef:
    name: qm1
  channelName: ORDERS.APP
  type: svrconn
  description: Application server-connection channel
  maxMsgLength: 4194304
  transportType: tcp
