apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kurator-system

resources:
  - mq-credentials-secret.yaml
  - queuemanagerconnection.yaml
  - queue.yaml
  - queue-alias.yaml
  - queue-remote.yaml
  - topic.yaml
  - channel.yaml
