locals {
  argocd_namespace = "argocd"
  argocd_host      = "argocd.localhost"
  state_dir        = var.state_dir != "" ? var.state_dir : "${path.module}/../.state"
}

resource "kubernetes_namespace_v1" "argocd" {
  count = var.enable_argocd ? 1 : 0

  metadata {
    name = local.argocd_namespace
  }
}

resource "kubernetes_secret_v1" "argocd_tls" {
  count = var.enable_argocd ? 1 : 0

  metadata {
    name      = var.tls_secret_name
    namespace = kubernetes_namespace_v1.argocd[0].metadata[0].name
  }

  type = "kubernetes.io/tls"

  data = {
    "tls.crt" = base64decode(var.tls_cert_string)
    "tls.key" = base64decode(var.tls_key_string)
  }
}

resource "helm_release" "argocd" {
  count = var.enable_argocd ? 1 : 0

  name             = "argocd"
  namespace        = kubernetes_namespace_v1.argocd[0].metadata[0].name
  create_namespace = false

  repository = "https://argoproj.github.io/argo-helm"
  chart      = "argo-cd"
  version    = "7.9.1"

  wait    = true
  timeout = 900

  values = [
    file("${path.module}/argocd-values.yaml"),
  ]

  set {
    name  = "server.ingress.ingressClassName"
    value = var.ingress_class_name
  }

  set {
    name  = "server.ingress.hostname"
    value = local.argocd_host
  }

  set {
    name  = "server.ingress.extraTls[0].hosts[0]"
    value = local.argocd_host
  }

  set {
    name  = "server.ingress.extraTls[0].secretName"
    value = var.tls_secret_name
  }

  set {
    name  = "configs.params.server\\.insecure"
    value = "true"
  }

  depends_on = [
    helm_release.haproxy_ingress,
    kubernetes_secret_v1.argocd_tls,
  ]
}

data "kubernetes_secret_v1" "argocd_initial_admin" {
  count = var.enable_argocd ? 1 : 0

  metadata {
    name      = "argocd-initial-admin-secret"
    namespace = kubernetes_namespace_v1.argocd[0].metadata[0].name
  }

  depends_on = [helm_release.argocd]
}

resource "local_file" "argocd_env" {
  count = var.enable_argocd ? 1 : 0

  content = <<-EOT
    # Generated by Terraform (argocd.tf). Do not edit by hand.
    export ARGOCD_URL='https://${local.argocd_host}:30443/'
    export ARGOCD_ADMIN_USER='admin'
    export ARGOCD_ADMIN_PASSWORD='${data.kubernetes_secret_v1.argocd_initial_admin[0].data["password"]}'
  EOT

  filename             = "${local.state_dir}/argocd.env"
  file_permission      = "0600"
  directory_permission = "0755"

  depends_on = [data.kubernetes_secret_v1.argocd_initial_admin]
}
